# TPM — plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'  # sane defaults, recommended

# your plugins go here
set -g @plugin 'tmux-plugins/tmux-yank'

# your other config goes here
setw -g mode-keys vi
set-option -g default-shell /bin/zsh
set -g mouse

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# keep this line at the very bottom of tmux.conf
run '~/.config/tmux/plugins/tpm/tpm'
